# Generated by Django 5.2.6 on 2026-03-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('insurance_type', models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('vehicle', 'Vehicle Insurance'), ('property', 'Property Insurance')], max_length=100)),
            ],
        ),
    ]
